name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Installing build dep
      run: sudo apt install bison flex libelf-dev
    - name: Running script to build minimal x86_64 os
      run: |
        git clone --recurse-submodules https://github.com/arjuncr/minimal_x86_64_os.git
        cd minimal_x86_64_os/build-script
        ./build_x86_64.sh --build-img 12 64

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # A file, directory or wildcard pattern that describes what to upload
         path: /home/runner/work/minimal_x86_64_os/minimal_x86_64_os/minimal_x86_64_os/build-script/image/
         
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2
      with:
        # Destination path
        path:  /home/runner/work/minimal_x86_64_os/minimal_x86_64_os/minimal_x86_64_os/build-script/output/
      
